
CREATE PROCEDURE SPLISTAGEM(
@TAB VARCHAR(MAX),
@COLUNA VARCHAR(MAX)

)
AS
BEGIN
   DECLARE @SQL VARCHAR(MAX)
      SET @SQL = ' SELECT ' + @COLUNA + ' FROM ' + @TAB;
   EXEC(@SQL)
END
GO

CREATE PROCEDURE SPCONSULTA(

@TABELA VARCHAR(MAX),
@COLUNA VARCHAR(MAX),
@ID VARCHAR(MAX)

)
AS
BEGIN 
   DECLARE @SQL VARCHAR(MAX)
   IF(@COLUNA = NULL)
      SET @SQL = 'SELECT * FROM ' + @TABELA;
   ELSE
      SET @SQL = ' SELECT * FROM ' + @TABELA + ' WHERE ' + @COLUNA + ' = ' + @ID;
   
   
   EXEC(@SQL)
END
GO
 