
CREATE PROCEDURE SPLISTAGEM(
@TAB VARCHAR(MAX),
@COLUNA VARCHAR(MAX),
@FILTRO VARCHAR(MAX),
@ORDEM VARCHAR(MAX)

)
AS
BEGIN
   DECLARE @SQL VARCHAR(MAX)
   IF(@FILTRO = NULL)
      SET @SQL = ' SELECT ' + @COLUNA + ' FROM ' + @TAB;
   ELSE
      SET @SQL = ' SELECT ' + @COLUNA + ' FROM ' + @TAB + ' ORDER BY ' + @FILTRO + '' + @ORDEM ;
   EXEC(@SQL)
END
GO

CREATE PROCEDURE SPCONSULTA(

@TABELA VARCHAR(MAX),
@COLUNA VARCHAR(MAX),
@ID VARCHAR(MAX)

)
AS
BEGIN 
   DECLARE @SQL VARCHAR(MAX)
   IF(@COLUNA = NULL)
      SET @SQL = 'SELECT * FROM ' + @TABELA;
   ELSE
      SET @SQL = ' SELECT * FROM ' + @TABELA + ' WHERE ' + @COLUNA + ' = ' + @ID;
   
   
   EXEC(@SQL)
END
GO

CREATE PROCEDURE SPDELETE (

@TABELA VARCHAR(MAX),
@ID VARCHAR(MAX)

)
AS
BEGIN

DECLARE @SQL VARCHAR(MAX)

SET @SQL = 'DELETE'+ @TABELA +'WHERE ID = '+ @ID;

EXEC(@SQL)
END
GO
 